# Generated by Django 3.2.8 on 2021-11-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cédula'),
        ),
    ]
