# Generated by Django 3.2.8 on 2021-10-30 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AlterField(
            model_name='menugrupo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='menugrupo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AlterField(
            model_name='menugrupo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AlterField(
            model_name='menugrupo',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
    ]
