# Generated by Django 3.2.9 on 2021-11-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis_radiografico',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_user', to='covid.medico'),
        ),
        migrations.AlterField(
            model_name='analisis_radiografico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_user', to='covid.paciente'),
        ),
    ]
