# Generated by Django 3.2.9 on 2021-11-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20211112_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Diagnostico',
            field=models.TextField(null=True, verbose_name='Diágnostico previo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='es_vacunado',
            field=models.BooleanField(null=True, verbose_name='¿Está usted vacunado contra el covid?'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='vacuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='covid.vacuna', verbose_name='Tipo de Vacuna'),
        ),
    ]
