# Generated by Django 3.2.8 on 2021-11-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_alter_user_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis_Radiografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_analisis', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_user', to='covid.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_user', to='covid.paciente')),
            ],
            options={
                'verbose_name': 'Analisis',
                'verbose_name_plural': 'Analisis',
            },
        ),
    ]
