# Generated by Django 3.2.8 on 2021-11-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_especialidadmedico_medico_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
