# Generated by Django 3.2.9 on 2021-11-13 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_alter_user_genero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisis_radiografico',
            options={'permissions': (('puede_ver_contenido_medico', 'Puede ver contenido para medicos'), ('puede_ver_contenido_paciente', 'Puede ver contenido solo para pacientes')), 'verbose_name': 'Analisis', 'verbose_name_plural': 'Analisis'},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Diágnostico previo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='es_vacunado',
            field=models.BooleanField(default=True, verbose_name='¿Está usted vacunado contra el covid?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='vacuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='covid.vacuna', verbose_name='Tipo de Vacuna'),
        ),
    ]
