# Generated by Django 3.2.9 on 2021-11-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20211113_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisis_radiografico',
            options={'permissions': (('Can_view_Analisis_paciente_only', 'Puede ver el analisis de acuerdo al paciente logeado'),), 'verbose_name': 'Analisis', 'verbose_name_plural': 'Analisis'},
        ),
    ]
