# Generated by Django 3.2.9 on 2021-11-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_alter_analisis_radiografico_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisis_radiografico',
            options={'permissions': (('see_view_Analisis_paciente_only', 'Can_view_Analisis_paciente_only'),), 'verbose_name': 'Analisis', 'verbose_name_plural': 'Analisis'},
        ),
    ]
