# Generated by Django 3.2.9 on 2021-11-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_alter_analisis_radiografico_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'permissions': (('see_view_report', 'Can_view_report'),)},
        ),
    ]
