# Generated by Django 3.2.9 on 2021-11-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0009_alter_medico_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis_radiografico',
            name='fecha',
            field=models.TimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
    ]
