# Generated by Django 3.2.9 on 2021-11-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0010_alter_analisis_radiografico_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis_radiografico',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
    ]
