# Generated by Django 3.2.9 on 2021-11-14 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0013_auto_20211114_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis_radiografico',
            name='estado_registro',
            field=models.BooleanField(default=True, verbose_name='Estado del registro'),
        ),
        migrations.AddField(
            model_name='analisis_radiografico',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisis_radiografico',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='analisis_radiografico',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='analisis_radiografico',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
    ]
